[package]
name = "orbutils"
description = "The Orbital Utilities"
repository = "https://github.com/redox-os/orbutils"
version = "0.1.5"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[[bin]]
name = "editor"
path = "src/editor/main.rs"

[[bin]]
name = "launcher"
path = "src/launcher/main.rs"

[[bin]]
name = "terminal"
path = "src/terminal/main.rs"

[[bin]]
name = "viewer"
path = "src/viewer/main.rs"

[dependencies]
orbclient = "0.1"
orbtk = "0.1"
