[package]
name = "orbutils"
description = "The Orbital Core Utilities"
repository = "https://github.com/redox-os/orbutils"
version = "0.1.0"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[[bin]]
name = "editor"
path = "src/editor.rs"

[dependencies]
orbtk = "0.1"
